### ISSUE TITLE
Can't use CommonJS with ES6

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/tsify#109]
It's common to want to use ES6, but supporting CommonJS module output should be supported. Currently it's being overridden by `None` (https://github.com/TypeStrong/tsify/blob/e75bde695619879d7f9acb1d2faa5b83ec58435d/lib/Tsifier.js#L57-L59). I think it'd make more sense for it to use the users option, then fallback if it's a necessity (is there some advantage of having None and Browserify together?)

**Comment by smrq** [comment]
Oh that's a holdover from an earlier compiler version when CommonJS output
was not supported for ES6, I think. Should be no problem changing that.

**Comment by cherrydev** [comment]
Actually, it's still broken until TS 1.8 :(

https://github.com/Microsoft/TypeScript/issues/5594

**Comment by blakeembrey** [comment]
That sucks, sorry! Hopefully these'll be fixed soon since it really hampers usage.

**Comment by polkovnikov-ph** [comment]
They've fixed it, yet it still doesn't work for me for some other reason.

SyntaxError: Unexpected token (4:12) while parsing C:\projpath\server\source\index.ts while parsing file: C:\projpath\server\source\index.ts
    at DestroyableTransform.end [as _flush] (C:\projpath\node_modules\browserify\node_modules\insert-module-globals\index.js:97:21)
    at DestroyableTransform.<anonymous> (C:\projpath\node_modules\readable-stream\lib\_stream_transform.js:123:12)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (C:\projpath\node_modules\readable-stream\lib\_stream_writable.js:501:12)
    at finishMaybe (C:\projpath\node_modules\readable-stream\lib\_stream_writable.js:509:7)
    at endWritable (C:\projpath\node_modules\readable-stream\lib\_stream_writable.js:521:3)
    at DestroyableTransform.Writable.end (C:\projpath\node_modules\readable-stream\lib\_stream_writable.js:486:5)
---------------------------------------------
    at Labeled.Readable.on (C:\projpath\node_modules\readable-stream\lib\_stream_readable.js:720:33)
    at module.exports (C:\projpath\node_modules\read-only-stream\index.js:28:12)
    at Browserify.bundle (C:\projpath\node_modules\browserify\index.js:772:18)
    at Gulp.<anonymous> (C:\projpath\gulpfile.js:29:11)
    at module.exports (C:\projpath\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\projpath\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\projpath\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\projpath\node_modules\orchestrator\index.js:134:8)
    at C:\Users\user\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
	
while trying to compile a file starting as

	///<reference path="../../typings/tsd.d.ts" />
	'use strict';
	require('source-map-support').install();

	import * as express from 'express'; // seems like it's talking about this line
	import * as path from 'path';
	import * as logger from 'morgan';
	import * as cookieParser from 'cookie-parser';
	import test from './test';
	
	...
	
with

	var config = {
		debug: true
	};
	var tsConfig = {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
		"removeComments": true,
		"noImplicitAny": true,
		"typescript": typescript
    };
	var b = browserify(config)
		.plugin(tsify, tsConfig)
		.add('./source/index.ts')
		.transform(babelify, {
			presets: ['es2015', 'react']
		});
	
	return b.bundle()
		.pipe(source('index.js'))
		.pipe(gulp.dest('./target'));

**Comment by smrq** [comment]
Now that we're on TS 1.8, this override has been removed.
