### ISSUE TITLE
Command line approach (Example Usage) fails with "Error: Cannot find module 'tsify' from ..."

### ISSUE THREAD

**Issue by dmitrijs** [TypeStrong/tsify#115]
```
d:\>echo "var s:string = 'test'; console.log(s);" > main.ts

d:\>npm install -g browserify tsify
C:\Program Files\nodejs\browserify -> C:\Program Files\nodejs\node_modules\browserify\bin\cmd.js
tsify@0.13.2 C:\Program Files\nodejs\node_modules\tsify
├── debuglog@1.0.1
├── convert-source-map@1.1.3
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.5)
├── typescript@1.7.5
└── lodash@3.10.1

browserify@13.0.0 C:\Program Files\nodejs\node_modules\browserify
├── https-browserify@0.0.1
├── tty-browserify@0.0.0
├── htmlescape@1.1.0
├── path-browserify@0.0.0
├── duplexer2@0.1.4
├── punycode@1.4.0
├── string_decoder@0.10.31
├── browser-resolve@1.11.1
├── isarray@0.0.1
├── through2@2.0.1
├── constants-browserify@1.0.0
├── os-browserify@0.1.2
├── inherits@2.0.1
├── process@0.11.2
├── stream-browserify@2.0.1
├── assert@1.3.0
├── defined@1.0.0
├── domain-browser@1.1.7
├── xtend@4.0.1
├── read-only-stream@2.0.0
├── querystring-es3@0.2.1
├── timers-browserify@1.4.2
├── util@0.10.3
├── deps-sort@2.0.0
├── events@1.1.0
├── concat-stream@1.5.1 (typedarray@0.0.6)
├── parents@1.0.1 (path-platform@0.11.15)
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── has@1.0.1 (function-bind@1.1.0)
├── readable-stream@2.0.5 (process-nextick-args@1.0.6, util-deprecate@1.0.2, core-util-is@1.0.2)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, jsonify@0.0.0, array-map@0.0.0)
├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
├── subarg@1.0.0 (minimist@1.2.0)
├── labeled-stream-splicer@2.0.0 (stream-splicer@2.0.0)
├── stream-http@2.1.1 (builtin-status-codes@2.0.0, to-arraybuffer@1.0.1)
├── shasum@1.0.2 (sha.js@2.4.4, json-stable-stringify@0.0.1)
├── buffer@4.5.0 (ieee754@1.1.6, isarray@1.0.0, base64-js@1.0.4)
├── JSONStream@1.0.7 (through@2.3.8, jsonparse@1.2.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── resolve@1.1.7
├── browserify-zlib@0.1.4 (pako@0.2.8)
├── syntax-error@1.1.5 (acorn@2.7.0)
├── browser-pack@6.0.1 (umd@3.0.1, combine-source-map@0.7.1)
├── crypto-browserify@3.11.0 (create-hmac@1.1.4, randombytes@2.0.2, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@5.0.2, create-ecdh@4.0.0, browserify-cipher@1.0.0, public-encrypt@4.0.0, browserify-sign@4.0.0)
├── insert-module-globals@7.0.1 (is-buffer@1.1.2, combine-source-map@0.7.1, lexical-scope@1.2.0)
└── module-deps@4.0.5 (stream-combiner2@1.1.1, detective@4.3.1)

d:\>browserify.cmd main.ts -p [ tsify --noImplicitAny ] -o bundle.js
C:\Programs\nvm\v4.2.6\node_modules\browserify\node_modules\resolve\lib\sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module 'tsify' from 'd:\'
    at Function.module.exports [as sync] (C:\Programs\nvm\v4.2.6\node_modules\browserify\node_modules\resolve\lib\sync.js:33:11)
    at Browserify.plugin (C:\Programs\nvm\v4.2.6\node_modules\browserify\index.js:354:29)
    at C:\Programs\nvm\v4.2.6\node_modules\browserify\bin\args.js:126:15
    at Array.forEach (native)
    at module.exports (C:\Programs\nvm\v4.2.6\node_modules\browserify\bin\args.js:121:10)
    at Object.<anonymous> (C:\Programs\nvm\v4.2.6\node_modules\browserify\bin\cmd.js:6:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

d:\>
```

Are there some special steps that are needed when using **globally** installed `tsify`?

**Comment by blakeembrey** [comment]
@dmitrijs Browserify transforms should always be installed locally. I would recommend you use local dependencies always. Is there a reason you don't want to use local dependencies? Here's some people asking about this already: https://github.com/substack/node-browserify/issues/1206.
