### ISSUE TITLE
TypeError: Object # has no method 'debuglog'  

### ISSUE THREAD

**Issue by iandonov** [TypeStrong/tsify#130]
cmd.exe /c gulp -b "C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master" --color --gulpfile "C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\Gulpfile.js" build
 [22:03:38] Using gulpfile C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\Gulpfile.js
 [22:03:38] Starting 'patch-io'...
 [22:03:38] Starting 'patch-ng'...
 [22:03:38] Starting 'sass'...
 [22:03:38] Starting 'copy.fonts'...
 [22:03:38] Starting 'copy.html'...
 [22:03:38] Starting 'copy.scripts'...
 [22:03:38] Finished 'patch-io' after 63 ms
 [22:03:38] Finished 'patch-ng' after 57 ms
 [22:03:38] Finished 'copy.scripts' after 49 ms
 [22:03:38] Finished 'copy.html' after 112 ms
 [22:03:38] Finished 'copy.fonts' after 114 ms
 [22:03:39] Finished 'sass' after 995 ms
 Process terminated with code 1.
 [22:03:39] Starting 'build'...
 [22:03:39] 'build' errored after 103 ms
**[22:03:39] TypeError: Object # has no method 'debuglog'
 at Object. (C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\node_modules\tsify\lib\Tsifier.js:5:31)
** at Module._compile (module.js:456:26)
 at Object.Module._extensions..js (module.js:474:10)
 at Module.load (module.js:356:32)
 at Function.Module._load (module.js:312:12)
 at Module.require (module.js:364:17)
 at require (module.js:380:17)
 at tsify (C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\node_modules\tsify\index.js:11:16)
 at Browserify.plugin (C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\node_modules\browserify\index.js:351:9)
 at bundleTask (C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\Gulpfile.js:154:7)

at Gulp.gulp.task.autoprefixerOpts.browsers (C:\Temp\build2016-vsmobile-master\build2016-vsmobile-master\Gulpfile.js:64:10)

**Comment by smrq** [comment]
What version of Node are you using?  `debuglog` has been a part of `util` since v0.12.

**Comment by iandonov** [comment]
v0.12.2

**Comment by smrq** [comment]
OK, reverting this change and making it a major version bump since it was apparently a breaking change for some versions of Node v0.12.  It'll be back in the next major version, so if you need to update further I would recommend updating your version of Node.

**Comment by conceptdeluxe** [comment]
When working with IntelliJ also verify which Node interpreter is selected (Settings: Languages & Frameworks > Node.js and NPM). I was wondering why I was getting the above error while having Node.js 6.2 installed. IntelliJ actually used my legacy Node.js installation as default, thus debuglog was missing.
