### ISSUE TITLE
Support for Typescript 2.0 (typescript@next)

### ISSUE THREAD

**Issue by jmlee2k** [TypeStrong/tsify#149]
When attempting to use the latest nightly build (Version 1.9.0-dev.20160623-1.0) in place of the bundled typescript compiler, it fails with the following message:

`[14:34:35] TypeError: Cannot read property 'useCaseSensitiveFileNames' of null
    at matchFileNames (c:\work\browesrify-test\node_modules\typescript\lib\typescript.js:45447:29)
    at getFileNames (c:\work\browesrify-test\node_modules\typescript\lib\typescript.js:45296:20)
    at parseJsonConfigFileContent (c:\work\browesrify-test\node_modules\typescript\lib\typescript.js:45244:18)
    at parseOptions (c:\work\browesrify-test\node_modules\tsify\lib\Tsifier.js:75:16)
    at new Tsifier (c:\work\browesrify-test\node_modules\tsify\lib\Tsifier.js:109:23)
    at tsify (c:\work\browesrify-test\node_modules\tsify\index.js:12:16)
    at Browserify.plugin (c:\work\browesrify-test\node_modules\browserify\index.js:351:9)
    at Gulp.<anonymous> (c:\work\browesrify-test\gulpfile.js:154:5)
    at module.exports (c:\work\browesrify-test\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\work\browesrify-test\node_modules\orchestrator\index.js:273:3)`

**Comment by Matthalp** [comment]
+1 

typescript@next makes managing Typescript definition files much easier, so it would be great to have support in tsify. More details here:
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by Loilo** [comment]
Isn't this solved by #154 ?

**Comment by basarat** [comment]
Its been solved since `1.0.0`. Enjoy :rose: ❤️

**Comment by basarat** [comment]
Yup #154 and #155 were the relevant fixes :rose:

**Comment by Loilo** [comment]
This doesn't support [TS 2.0 module resolution](https://github.com/Microsoft/TypeScript/issues/5039) features, does it? At least I can't get it running.

**Comment by OliverJAsh** [comment]
Works for me, thanks!

**Comment by Loilo** [comment]
I just opened [a new issue](160) for the module resolution case.
