### ISSUE TITLE
Cannot read property 'useCaseSensitiveFileNames' of null

### ISSUE THREAD

**Issue by basarat** [TypeStrong/tsify#155]
With TypeScript latest `parseJsonConfigFileContent` will throw an error:

```
TypeError: Cannot read property 'useCaseSensitiveFileNames' of null
```

Here is the call : https://github.com/TypeStrong/tsify/blob/97eaeec38d9ac0088973df801d753b0c7a1cbb97/lib/Tsifier.js#L75

**Comment by rolandjitsu** [comment]
@basarat has this been solved? I seem to be having the same issue.

**Comment by basarat** [comment]
@rolandjitsu yes. Fixed since version 1.0.0 :rose:

**Comment by rolandjitsu** [comment]
@basarat ok, thanks. I think it might be that some other package is referencing an older version. I'm using Ionic 2, and one of their npm packages uses this package, but it seems it's at version `^0.14.1`.

**Comment by rolandjitsu** [comment]
Now I get the following:
```bash
Caught exception:
 Error: ENOENT: no such file or directory, realpath '/Users/rolandjitsu/Projects/infarm/operator/node_modules/typescript/lib/lib.es7.d.ts'
    at Error (native)
    at Object.realpathSync (fs.js:1574:18)
    at /Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic-gulp-browserify-typescript/node_modules/tsify/index.js:62:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic-gulp-browserify-typescript/node_modules/tsify/index.js:62:6)
    at DestroyableTransform.<anonymous> (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic-gulp-browserify-typescript/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/Users/rolandjitsu/Projects/infarm/operator/node_modules/ionic-gulp-browserify-typescript/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12) 
```

Is tsify referencing that file somewhere?

**Comment by rolandjitsu** [comment]
Ooops, my bad, I was referencing that file. Sorry 👍
