### ISSUE TITLE
Fresh Install Fails with "Cannot read property 'basedir' of undefined" error

### ISSUE THREAD

**Issue by azer** [TypeStrong/tsify#157]
Trying this command on:

```
$ browserify a.ts -p [ tsify --noImplicitAny ]
```

on this file;

```typescript
class Yo {}
```

Fails with following error:

```
  λ  browserify a.ts -p [ tsify --noImplicitAny ]
/private/tmp/node_modules/tsify/lib/Tsifier.js:59
				opts.project || bopts.basedir || currentDirectory,
				                     ^

TypeError: Cannot read property 'basedir' of undefined
    at parseOptions (/private/tmp/node_modules/tsify/lib/Tsifier.js:59:26)
    at new Tsifier (/private/tmp/node_modules/tsify/lib/Tsifier.js:114:23)
    at tsify (/private/tmp/node_modules/tsify/index.js:12:16)
    at Browserify.plugin (/Users/azer/dev/node-browserify/index.js:412:5)
    at /Users/azer/dev/node-browserify/bin/args.js:86:15
    at Array.forEach (native)
    at module.exports (/Users/azer/dev/node-browserify/bin/args.js:81:10)
    at Object.<anonymous> (/Users/azer/dev/node-browserify/bin/cmd.js:6:26)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```

Any ideas ?

**Comment by basarat** [comment]
In your `package.json` you have it as a transform? **you shouldn't**. Please share the `package.json`. I had the same issue once :) :rose:

**Comment by cartant** [comment]
The command that you've used works fine, for me. What versions are you using? I'm using:

* Browserify 13.0.1
* Tsify 1.0.0

**Comment by azer** [comment]
@basarat I did not. Actually, in my second try, there wasn't even package.json

**Comment by cartant** [comment]
Closing this in the absence of further information. The problem cannot be reproduced using Browserify 13.0.1 and Tsify 1.0.0. Also, according to the stack trace in the original post, the `browserify` command is resolving to `/Users/azer/dev/node-browserify/` - which is not a standard NPM install.
