### ISSUE TITLE
 Cannot find module 'typescript'

### ISSUE THREAD

**Issue by Dj-jom2x** [TypeStrong/tsify#164]
sorry to bother you guys but i need help i got this error
```
    Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at tsify (/mnt/c/webserver/htdocs/system/node_modules/tsify/index.js:6:30)
    at Browserify.plugin (/usr/local/lib/node_modules/browserify/index.js:361:9)
    at /usr/local/lib/node_modules/browserify/bin/args.js:128:15
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/browserify/bin/args.js:123:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/browserify/bin/cmd.js:6:26)
```

why is that?
i already have tsify,browserify,typescript 1.8.10

i also try this i dunnu if i complete understand the usage sorry

browserify build.js > bundle.js
or
node build.js
```
    Error: Cannot find module 'typescript' from '/mnt/c/webserver/htdocs/system/node_modules/tsify'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by Dj-jom2x** [comment]
nvm my mistake i installed typescript globally XD
