### ISSUE TITLE
Requiring Streams from browserify

### ISSUE THREAD

**Issue by pulasthibandara** [TypeStrong/tsify#218]
I have a gulp task where I use [b.require](https://github.com/substack/node-browserify#brequirefile-opts) to require a stream input to browserify.

```javascript
var b = browserify({
        entries: './src/js/app.ts',
        debug: true
    })
    .plugin(tsify)
    .exclude('nzs-templates')
    .exclude('nzs-envConfig')
    // require streams from functions templates() and jsConfig()
    .require( templates(), { expose: 'nzs-templates', basedir: './' })
    .require( jsConfig(), { expose: 'nzs-envConfig', basedir: './' })
    .transform('browserify-shim')
    .transform("babelify", {presets: ["es2015"]});

    if( flag( envConfig.JS_MINIFY ) ) {
        b.transform( { global: true }, 'uglifyify');
    }
    
    return b.bundle()
        .pipe(source('app.js'))
        .pipe(buffer())
        .pipe(gulpIf( flag( env.JS_MAPS ),  sourcemaps.init({loadMaps: true}) ) )
        // Add transformation tasks to the pipeline here.
        .pipe( gulpIf( flag( envConfig.JS_MINIFY ), uglify() ) )
        .on('error', util.log)
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(  path.join( envConfig.BUILD_PATH, '/js' ) ))
        .pipe( notify({
            "title": "Gulp",
            "message": "JS compiled!",
            "sound": "Frog", // case sensitive
        }) );
```

The functions templates() and jsConfig() outputs a stream
```javascript
function templates ()
{
    return gulp.src( path.join( config.jsDir, '/**/*.tpl.html' ) )
        .pipe( templateCache({
            module: 'nzs-templates',
			standalone: true
		} ) )
        .pipe( through.obj( function ( chunk, env, cb ) {
            if (chunk.isStream()) {
                self.emit('error', new gutil.PluginError(PLUGIN_NAME, 'Cannot operate on stream'));
            }
            else if (chunk.isBuffer()) {
                this.push(chunk.contents);
            }

            cb();
        } ) );
}
```

I'm in the process of migrating a js angular project to ts and this used to work fine just with browserify. I get the following error with tsify when trying to require these streams

```
Error: ENOENT: no such file or directory, lstat 'C:\Users\Bandarp\projects\product-manager\ui\_stream_2.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at realpathSync (fs.js:1662:21)
    at Function.realpathSync (C:\Users\Bandarp\projects\product-manager\ui\node_modules\fs.realpath\index.js:48:12)
    at C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\index.js:70:44
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\index.js:70:6)
    at DestroyableTransform.<anonymous> (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:475:12)
    at finishMaybe (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:483:7)
    at endWritable (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:495:3)
    at DestroyableTransform.Writable.end (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:465:41)
    at DestroyableTransform.onend (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_readable.js:500:10)
```

**Comment by cartant** [comment]
So long as the streams don't contain TypeScript content, it should be possible to implement a fix for this. I'll have a look at it this evening (i.e. in about 12 or so hours).

**Comment by pulasthibandara** [comment]
Thanks, that was extremely quick. streams are just two generated angular modules from `gulp-angular-templatecache` and `gulp-ng-config`. No ts code.

**Comment by cartant** [comment]
This should be fixed by https://github.com/TypeStrong/tsify/commit/8b132141a7678c5514c3214c33264c1c998b9b90

I've published version 2.0.4 to NPM.

**Comment by pulasthibandara** [comment]
Hi, I just tested it now. However this lead to another error which is further down the process I guess. The files get filtered in the `flush` method. However it seems that the tsifier still tries to parse it as a physical file.

```bash
[11:32:50] Browserify Error Error: tsify: no compiled file for C:\Users\Bandarp\projects\product-manager\ui\_stream_2.js
    at Tsifier.getCompiledFile (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:289:24)
    at Tsifier.getCompiledFile (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:295:16)
    at DestroyableTransform.flush [as _flush] (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:273:24)
    at DestroyableTransform.<anonymous> (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:475:12)
    at finishMaybe (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:483:7)
    at endWritable (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:495:3)
    at DestroyableTransform.Writable.end (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:465:41)
    at DuplexWrapper.<anonymous> (C:\Users\Bandarp\projects\product-manager\ui\node_modules\stream-combiner2\node_modules\duplexer2\index.js:29:14)
    at DuplexWrapper.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DuplexWrapper.emit (events.js:185:7)
    at finishMaybe (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:485:14)

[11:32:51] Browserify Error Error: tsify: no compiled file for C:\Users\Bandarp\projects\product-manager\ui\_stream_1.js
    at Tsifier.getCompiledFile (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:289:24)
    at Tsifier.getCompiledFile (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:295:16)
    at DestroyableTransform.flush [as _flush] (C:\Users\Bandarp\projects\product-manager\ui\node_modules\tsify\lib\Tsifier.js:273:24)
    at DestroyableTransform.<anonymous> (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:475:12)
    at finishMaybe (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:483:7)
    at endWritable (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:495:3)
    at DestroyableTransform.Writable.end (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:465:41)
    at DuplexWrapper.<anonymous> (C:\Users\Bandarp\projects\product-manager\ui\node_modules\stream-combiner2\node_modules\duplexer2\index.js:29:14)
    at DuplexWrapper.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DuplexWrapper.emit (events.js:185:7)
    at finishMaybe (C:\Users\Bandarp\projects\product-manager\ui\node_modules\readable-stream\lib\_stream_writable.js:485:14)
```

**Comment by cartant** [comment]
Can you show me the code that imports/requires the stream-sourced content?

**Comment by cartant** [comment]
Also, you might want to have a look at the test that I added to see how it differs from what you are doing:

* [`test('with required stream', ...`](https://github.com/TypeStrong/tsify/blob/master/test/test.js#L568-L585)
* [`withRequiredStream/x.ts`](https://github.com/TypeStrong/tsify/blob/master/test/withRequiredStream/x.ts)

**Comment by pulasthibandara** [comment]
Hi, I wonder if its because gulp plugins return vinyl streams. I added a failing test to check.

[https://github.com/pulasthibandara/tsify/commit/a1a6d17ae9177c7fc9319e25acb9239b0ea35641](url)

**Comment by pulasthibandara** [comment]
btw, this is how I require the two modules

```javascript
//index.ts
require( "nzs-templates" );
require( "nzs-envConfig" );
```

**Comment by cartant** [comment]
The requires look fine. I will check out the vinyl streams thing. Thanks for writing a test!

**Comment by cartant** [comment]
Something is going wrong upstream (pardon the pun). By the time the Browserify 'row' for the stream shows up, the row's `source` property is set to `"[object Object]"` which is obviously not value source code.

Do you have anything similar working with Browserify without tsify?

**Comment by cartant** [comment]
Messing with Browserify streams is not something I often do. However, I answered an SO question and the OP was using vinyl. He managed to get things working with vinyl streams, so you might find something useful in there: http://stackoverflow.com/a/39433893/6680611

Unless you can get Browserify to work with the streams you are using, there's not much that can be done at this end.

If you are going to look further into it, it's [this line of code](https://github.com/TypeStrong/tsify/blob/master/index.js#L61) you'll want to poke around with:

    .filter(function (row) { return row.source === undefined; })

Add some logging:

    .filter(function (row) { log(JSON.stringify(row); return row.source === undefined; })

And then run gulp with `NODE_DEBUG` set like this:

    NODE_DEBUG=tsify gulp ...

Then you'll see the 'rows' that are passed from Browserify. Until the stream row's `source` is something other than `"[object Object]"`, it's not going to work. You can use the `NODE_DEBUG` thing with the tests, too:

    NODE_DEBUG=tsify npm run test-main

**Comment by pulasthibandara** [comment]
Yeah, sorry for the trouble. I don't think its an issue with vinyl streams since I tried it with a text stream and got the same error. I'll check my code first. Might be an issue with how I configured it. Will update when I get it working.

Thanks!

**Comment by cartant** [comment]
No worries.

**Comment by pulasthibandara** [comment]
I couldn't find the cause.
I re-created the issue in this simple sample, which doesn't use gulp or vinyl streams.

https://github.com/pulasthibandara/tsify-issue-218

**Comment by cartant** [comment]
Thanks. The test should really be failing, too. It also attempts to transform `_stream_1.js`, but `flush` isn't being called on the transform stream, so it's not failing.

**Comment by cartant** [comment]
I've had a look at it. The difference was that you had `allowJs` enabled and the test didn't. So that test wasn't trying to transform the JS stream. I've updated the test and I've tracked the ignored stream files so that they can be ignored in the transform, too.

**Comment by pulasthibandara** [comment]
Hi Just tested the new code,
The commit bfecaa10e2a03b9ed476958bfb58fc5921bb719a is working!.
I got some errors on 2.0.7 due to `Tsifier.ignoredFiles` being overridden from `getCompiledFile` method.

Thanks for fixing this so quickly. Awesome work @cartant!
