### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by davidwarford** [TypeStrong/tsify#271]
Hey i just decided I would move from using tsc and browserify separately to using tsify. it worked just fine but after installing and using tsify it gives a strange error which is not even in my own code.
```
PS C:\Users\david\repos\ISSEditor> browserify ./src/main.ts [ tsify --noImplicitAny ] -o  ./dist/ISSEditor.js
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:139:9)
    at Deps._transform (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\module-deps\index.js:110:32)
    at Deps.Transform._read (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Deps.Transform._write (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at Labeled.Pipeline._write (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\stream-splicer\index.js:70:22)
    at doWrite (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at clearBuffer (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:548:7)
    at onwrite (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:475:7)
    at WritableState.onwrite (C:\Users\david\emsdk\node\12.18.1_64bit\bin\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:180:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by cartant** [comment]
I don't have time to help you debug this and, regardless of that, you've not provided a reproduction of the problem. Generally, bug reports like this are unactionable.

tsify's [debug logging](https://github.com/TypeStrong/tsify/blob/master/CONTRIBUTING.md#debugging) might be of some help to you. And there a bunch of working examples in the `examples` directory. You can compare those with your situation to see what's different.
