### ISSUE TITLE
can't find npm module angular2

### ISSUE THREAD

**Issue by episodeyang** [TypeStrong/tsify#95]
Hi,

I have a project setup as

```
/ project_folder
|---/app
|   |---index.ts
|   |---vendor.json
|---/gulpfile.js
|---|---index.js
|---package.json
|---/node_modules
```

note that the gulpfile.js is a folder. The `gulpfile.js/index.js` look like:

```javascript
gulp.task('vendor-js', function (done) {
    var vendorGlob = 'app/vendor.json';
    var b = browserify();
    b
        .plugin(tsify, {
            target: "es6",
            noImplicitAny: true
        })
        .transform(babelify)
        .require(packages)
        .on('update', function () {
            return vendorBundle(b);
        });
    return vendorBundle(b);
    function vendorBundle(watcher) {
        return watcher
            .bundle()
            .pipe(source(bundlePath))
            .pipe(buffer())
            .pipe(rename({extname: '.min.js'}))
            .pipe(sourcemaps.init({loadMaps: !process.env.production})) // loads map from browserify file
            //.pipe(uglify({compress: process.env.production}))
            // Add transformation tasks to the pipeline here.
            .pipe(sourcemaps.write('./')) // writes .map file
            .pipe(gulp.dest(config.dist))
            .pipe(browserSyncInstance.stream({once: true}));
    }
});
```

I have angular2 installed via

```shell
npm install -D angular2
```

yet when I run `gulp vendor-js`, I get the following error message:

```shell
Error: ENOENT, no such file or directory '.../project_folder/app/angular2'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at Object.realpathSync (fs.js:1383:21)
    at .../project_folder/app/node_modules/tsify/index.js:57:38

```

**Comment by aciccarello** [comment]
> Error: ENOENT, no such file or directory '.../project_folder/app/angular2'

I'm wondering why are there three periods before project_folder?

**Comment by smrq** [comment]
Closing old issues.
